spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
reggie:
  path: D:\img\
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true